### PR TITLE
Fix dependency conflict for issue

### PR DESCRIPTION
**Pull request by NeolithEra**
#26

### CODE REVIEW

**Comment by NeolithEra** [comment]
@henning96 
Could you please help me review this issue?    
Thank you very much!

BTW, dependency conflict problems are very common in practice in python ecosystem.
I have encountered the issues several times. What's your oppinion on the challenges of detecting and repairing such issues?
And how to avoid dependency conflict problems among python projects, especially from the ecosystem's perspective?

**Comment by PyWaves** [comment]
Wouldn't it be better to fix it to base58 == 0.2.5?

**Comment by henning96** [comment]
This is a very specific problem depending on your environment.
I recommend to setup a virtual environment instead.
Python actually already provides a common solution for these kind of problems called virtualenv: https://virtualenv.pypa.io/en/latest/. It is meant to prevent package versioning issues.
You can setup a clean environment for your gateway with this tool where these kind of problems should not occur.

Because there is already a common solution for versioning conflicts, I won't merge this. I hope you understand.

**Comment by henning96** [comment]
If this does not work, we can think of merging this. I'ts possible that Pip will still resolve to the newer version. But anyway, I always recommend to use virtual environments because Python is known to have these kind of problems.

**Comment by NeolithEra** [comment]
@henning96 hi, thanks for your feedback.
I worked on a virtual environment and still got the installation failure, as shown in the following pictures：

**Comment by henning96** [comment]
Hi @NeolithEra, sorry that it took so long. I was able to reproduce your problem. It worked for me first, but in a clean environment it is broken. Maybe it is also related to the packages that are already installed. I am not sure. But anyways, it must at least work in a clean environment.
But, we cannot merge it like this. Simply removing the dependency cannot be a solution.
For now, I will simply set the PyWaves and base58 dependencies to a fixed version like @PyWaves did suggest. That will make the install work again (and will swallow any security fixes...).
From my perspective it would be the best that @PyWaves would adjust their dependencies to be more flexible.

**Comment by henning96** [comment]
https://github.com/jansenmarc/WavesGatewayFramework/pull/28

**Pull request closed without merging**
